server:
  error:
    include-stacktrace: never
    include-message: never
spring:
  datasource:
    url: jdbc:h2:mem:test_db
    username: sa
    password: sa
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      platform: h2
      continue-on-error: false
