server:
    error:
        include-stacktrace: never
        include-message: never
spring:
    datasource:
        url: jdbc:h2:mem:test_db
        username: sa
        password: sa
    jpa:
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                format_sql: true
        show-sql: true
